### ISSUE TITLE
Document undocumented or barely documented features.

### ISSUE THREAD

**Issue by DerBunman** [DerBunman/DieBenutzerumgebung#18]
Depends on
- [ ] #19 DFP file format
- [ ] #24 Document dotfiles and dfp commands
- [x] #13 Update README.md

**Comment by DerBunman** [comment]
no longer relevant
